learning_templates/basic_app/urls.py
from . import views
from django.urls import path,include
#TEMPLATE TEAGGING!!THE NAMING CONVENTION
app_name = 'basic_app'
urlpatterns = [
    path('',views.index,name="index"),
    path('other/',views.other,name="other"),
    path('relative/',views.relative,name="relative"),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return  render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-default  navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{%url 'basic_app:other'%}">other</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block%}
    <!-- Anything outside this will be inherited if you extend
    all the data outside -->
    {% endblock %}
</div>

</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
 <h1>Welcome to the INDEX!!</h1>
<h1>this is index html page showing </h1>
<!-- syntax wise they should both touch each other -->
<h1>{{ text|cut:'world'  }}
</h1>
<h1>{{ number|add:"99" }}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>welcome to the OTHER HTML!</h1>
<h1>example of template inheritance</h1>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>WELCOME TO THE RELATIVE HTML</h1>
<!-- I made a link to the 'other' url which points to other.html
and importantly app_name should not have any space while mentioning in the string-->
<a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
<!-- To view Admin page you've to do migrate first Django conventional way!-->
<a href="{% url 'admin:index' %}">admin view</a>
<a href="{% url 'basic_app:index' %}">LINK TO INDEX!</a>

</body>
</html>